### ISSUE TITLE
Is this extension obsoleted? Disable button ,whitelist selection both doesn't work

### ISSUE THREAD

**Issue by ZIEXED** [diegocr/CleanLinks#123]
The extension doesn't stop from cleaning links until I completely disable it as disabling it from it's icon doesn't work
Whitelist selection doesn't work
try the "send us an update" button in any app at Softpedia site as example 
those bugs causing dealing with this extension as very annoying
last update to this extension is from more than a year ago!?

**Comment by diegocr** [comment]
No, this extension is not obsoleted, it can only get obsolete if its cleaning feature is implemented in the browser itself. If you did mean abandoned, well, it's right that the AMO version wasn't updated in a year, but that's because no major issues were found. The version here on Github is 2.8a1 which includes some minor bug-fixes here and there, but i didn't think it worth a public release, yet. I think the next AMO version will be published as soon multi-process hits the stable branch/channel of Firefox, something which I still need to add support for. So, all in all, no, the extension is neither abandoned.

As for the issues you're experiencing, disabling the extension clicking the toolbar-button and whitelisting domains, both them work fine here.

What Firefox version and platform are you using?

as a temp workaround, you can go to the settings and manually enter the softpedia domain into the "Skip Domains" option.

**Comment by ZIEXED** [comment]
I'm using the latest FF version Win7 64
Did you test the softpedia button "send as un update" at any app page?
The site is already in the skip domains but the extension still miss it up
Disabling the extension from it's icon doesn't work for me and for other ppl "see the reviews at AMO"
I will test with a new profile with only this extension installed and reply [maybe tomorrow]

**Comment by ZIEXED** [comment]
Disabling the extension works now I can't reproduce this for now, once it happen again I will try to reproduce it
The other bug confirmed
to reproduce navigate to http://www.softpedia.com/get/Internet/Browsers/Mozilla-Firefox-Final.shtml
click "send us an update" button
the extension will clean the link to http://www.softpedia.com/get/Internet/Browsers/Mozilla-Firefox-Final.shtml
click Whitelist selection and try again it will keep clean the link
even adding the site to the skip domains won't help

win7 64
FF 45.0.2(32)
extension v2.7.1
