### ISSUE TITLE
Links not opening in background tabs

### ISSUE THREAD

**Issue by hackel** [diegocr/CleanLinks#58]
With CleanLinks 2.7a1 enabled, whenever I middle click on a link to open it in a new background tab, the new, cleaned link opens but in the foreground.  If I right-click on a link and choose to open in a new tab, it does so in the background, but CleanLinks isn't activated at all, so the clicks are still tracked.  I'm using Tab Utilities as well, so it's possible there is some kind of conflict there.  I'm using event delegation mode.

**Comment by diegocr** [comment]
This isn't something handled by _CleanLinks_, but rather by Firefox itself. That's why turning it off you can still experience the same behavior.

You have to go to the Firefox settings and activate _"When I open a link in a new tab, switch to it immediately."_

![clipboard image 6](https://cloud.githubusercontent.com/assets/734313/6098543/451854ee-afe2-11e4-8566-657e416f1d64.png)

**Comment by hackel** [comment]
lol, thank you for taking the time to give a screenshot and everything, but unfortunately this is not my issue.  I do not have that option enabled, and I do *not* experience it when I disable CleanLinks.  I should have added before that if I middle-click on a link that *doesn't* need to be cleaned, it opens in a background tab just fine.  It's only cleaned links that switch immediately for some reason.  I've just updated to the latest code and am still experiencing this issue.

**Comment by hackel** [comment]
Still experiencing this issue with the latest version, 2.7.  Please re-open this.
