### ISSUE TITLE
non-Event mode mangling links

### ISSUE THREAD

**Issue by atomGit** [diegocr/CleanLinks#68]
Clean Links 2.6.1.0
FF 34.0.5

(this issue is cross-posted @ https://tinyurl.com/nbej77l)

with CL default prefs, if Event mode is disabled, links are mangled and a hash (#) char is added to the end of the URI

reference: support site link @ https://addons.mozilla.org/en-US/firefox/addon/clean-links/

cleaned link: http://forums.mozillazine.org/viewtopic.php?f=48#
link should be: http://forums.mozillazine.org/posting.php?mode=reply&f=48&t=2749445

if the default RegExp is removed for 'Remove From Links', the problem is resolved, however i don't see any problem with the expression that would cause this, so maybe it's internal?

**Comment by diegocr** [comment]
Is there any good reason as to why did you turned off the Event mode? It became the default cleaning mode because the former/old method is quite slow, hence i don't recommend using it.

Digging into the issue itself, i can see this:

```bash
Clean Links Message @ 2015-01-09T20:10:41.768Z
> cleanlinks-cltrack
> http://outgoing.mozilla.org/v1/581ea3cffea643f0af85feab6799df90727719d390f9df4c8bc5e188a9021fd2/http%3A//forums.mozillazine.org/viewtopic.php%3Ff=48&t=2749445
> http://forums.mozillazine.org/viewtopic.php?f=48#
```

Apparently AMO is using a non-standard URL formatting, since the chunk `...f=48&t=2749445` should be properly url-encoded as `...f=48%26t%3d2749445` So, the non-Event mode algorithm thinks what is beyond the the last `&` is part of the original link and strips it off.

As for the hash mask char, it is intended, see #27 for further details.
